config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root to: 'pages#home'
    resources :shifts, only: %i[index]
    get '/shifts/calendar/:year/:month/', to: 'user_shifts#index', as: :shifts_with_calendar
    get '/shifts/calendar', to: 'user_shifts#index', as: :shifts_this_month_with_calendar
    patch 'shifts/:id/offer', to: 'user_shifts#offer', as: :offer_shift
    get 'shifts/:id/retract_offer', to: 'user_shifts#retract_offer', as: :retract_offer
    get 'shifts/:id/accept', to: 'user_shifts#accept', as: :accept_shift
    resources :user_shifts, only: %i[show] do
      resources :messages, only: :create
    end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    get '/profile', to: 'pages#profile'
    resources :users, only: %i[index show]
  end
end

app/models/user_shift.rb
class UserShift < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :shift
  has_many :messages

  validates :details, presence: true
  validate :user_cannot_have_less_bonuspoints

  def user_cannot_have_less_bonuspoints
    return unless user.present? && user.bonus_points.negative?

    errors.add(:bonus_points, "- it seems you don't have this many to add")
  end
end

app/controllers/user_shifts_controller.rb
class UserShiftsController < ApplicationController

  def show
    @user_shift = UserShift.find(params[:id])
    @message = Message.new
  end

  def index
    # this is if we want to display a calendar
    open_user_shifts = UserShift.all.select(&:open)
    my_user_shifts = current_user.user_shifts
    # if the searchword is exactly "open": index open shifts, else: index current user's shifts
    @year = params[:year].present? && year?(params[:year]) ? params[:year].to_i : Time.new.year
    # if there are year params: show calendar of that year, else: show calendar of current year
    @month = params[:month].present? && (1..12).include?(params[:month].to_i) ? params[:month].to_i : Time.new.month
    # if there are month params: show that month, else: show current month
    if params[:locale] == 'de'
      mth = %w[nil Januar Februar März April Mai Juni Juli August September Oktober November Dezember]
    else
      mth = %w[nil Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec]
    end
    @mth = mth[@month]
    @days = days(@month, @year)
    # range of amount of days in that month
    @current = Time.parse("#{@year}-#{@month}-01")
    @open_user_shifts = open_user_shifts.select do |user_shift|
      (user_shift.shift.date.year == @year && user_shift.shift.date.month == @month) \
      || (user_shift.shift.date.year == @current.next_month.year \
      && user_shift.shift.date.month == @current.next_month.month) \
      || (user_shift.shift.date.year == @current.last_month.year \
      && user_shift.shift.date.month == @current.last_month.month)
    end

    @my_user_shifts = my_user_shifts.select do |user_shift|
      (user_shift.shift.date.year == @year && user_shift.shift.date.month == @month) \
      || (user_shift.shift.date.year == @current.next_month.year \
      && user_shift.shift.date.month == @current.next_month.month) \
      || (user_shift.shift.date.year == @current.last_month.year \
      && user_shift.shift.date.month == @current.last_month.month)
    end

    @user = current_user
    respond_to do |format|
      format.html
      format.json
    end
  end

  def offer
    @user_shift = UserShift.find(params[:id])
    return unless @user_shift.user == current_user

    bps = strong_params[:bonus_points].to_i
    @user_shift.user.bonus_points -= bps
    if @user_shift.update(strong_params)
      @user_shift.user.update({ bonus_points: @user_shift.user.bonus_points })
      redirect_to user_shift_path(@user_shift)
    else
      @user_shift.open = false
      @user_shift.bonus_points = 0
      @message = Message.new
      render :show
    end
  end

  def retract_offer
    user_shift = UserShift.find(params[:id])
    return unless user_shift.user == current_user

    user_shift.user.bonus_points += user_shift.bonus_points
    user_shift.user.update!({ bonus_points: user_shift.user.bonus_points })
    user_shift.update!({ open: false, bonus_points: 0 })
    redirect_to user_shift_path(user_shift)
  end

  def accept
    user_shift = UserShift.find(params[:id])
    return unless user_shift.open

    current_user.bonus_points += user_shift.bonus_points
    user_shift.update!({ open: false, bonus_points: 0, user: current_user })
    current_user.update!({ bonus_points: user_shift.user.bonus_points })
    redirect_to user_shift_path(user_shift)
  end

  private

  def strong_params
    params.require(:user_shift).permit(:bonus_points, :open)
  end

  def year?(year)
    year.to_i.to_s == year && year.length == 4
  end

  def days(month, year)
    days = {}
    first = Time.parse("#{year}-#{month}-01")
    # determine first day of the month we want to show
    last_weekday_last_month = first.wday.zero? ? 6 : first.wday - 1
    days_last_month = (23..Time.days_in_month(first.last_month.month, first.last_month.year)).last(last_weekday_last_month)
    # determine the last days of the previous month that belong to this month's first week
    days[:last_month] = days_last_month.length.positive? ? days_last_month : []

    days_this_month = (1..Time.days_in_month(month, year))
    days[:this_month] = days_this_month
    # inject the amount of days this month
    missing = (days_this_month.last + last_weekday_last_month) % 7
    days[:next_month] = missing.zero? ? [] : (1..(7 - missing))
    # populate rest of last week with start of next month
    days
  end
end

app/views/user_shifts/_calendar.html.erb
<div class="wrapper-calendar" data-controller="calendar">
  <div class="calendar" data-calendar-target="container">
    <h2 class="d-flex justify-content-center"><strong><%= t 'your_calendar' %></strong></h2>
    <% shifts_my = my_user_shifts.map(&:shift) %>
    <% shifts_open = open_user_shifts.map(&:shift) %>
    <div class="calendar-dates">
      <div class="calendar-dates-weekdays">
        <div class="calendar-dates-weekdays-weekday"><%= t 'mon' %></div>
        <div class="calendar-dates-weekdays-weekday"><%= t 'tue' %></div>
        <div class="calendar-dates-weekdays-weekday"><%= t 'wed' %></div>
        <div class="calendar-dates-weekdays-weekday"><%= t 'thu' %></div>
        <div class="calendar-dates-weekdays-weekday"><%= t 'fri' %></div>
        <div class="calendar-dates-weekdays-weekday"><%= t 'sat' %></div>
        <div class="calendar-dates-weekdays-weekday"><%= t 'sun' %></div>
      </div>
      <div class="calendar-dates-days">
        <% days[:last_month].each do |day| %>
          <div class="calendar-dates-days-day calendar-dates-days-day--previous">
            <div class="calendar-dates-days-day-number">
              <%= day %>
            </div>
            <div class="calendar-dates-days-day-myshift">
              <% my_user_shifts.each do |user_shift| %>
                <% if user_shift.shift.date.day == day && user_shift.shift.date.month == current.last_month.month %>
                  <div class="calendar-shift">
                    <% case user_shift.shift.slot.name
                        when "Early" %>
                      <div class="calendar-shift-timeslot-early calendar-shift-timeslot-early--previous"><%= t 'early' %></div>
                    <% when "Late" %>
                      <div class="calendar-shift-timeslot-late calendar-shift-timeslot-late--previous"><%= t 'late' %></div>
                    <% when "Night" %>
                      <div class="calendar-shift-timeslot-night calendar-shift-timeslot-night--previous"><%= t 'night' %></div>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="calendar-dates-days-day-openshifts">
              <% if open_user_shifts.any? { |u_shift| u_shift.shift.date.day == day && u_shift.shift.date.month == current.last_month.month && u_shift.shift.date > DateTime.now } %>
                <div class="calendar-shift-circle"><i class="fas fa-bell"></i></div>
              <% end %>
            </div>
          </div>
        <% end %>
        <% days[:this_month].each do |day| %>
          <div class="calendar-dates-days-day <%= "calendar-dates-days-day--today" if day == Date.today.day && month == Date.today.month && year == Date.today.year %>">
            <div class="calendar-dates-days-day-number">
              <%= day %>
            </div>
            <div class="calendar-dates-days-day-myshift">
              <% my_user_shifts.each do |user_shift| %>
                <% if user_shift.shift.date.day == day && user_shift.shift.date.month == month %>
                  <div class="calendar-shift">
                    <% case user_shift.shift.slot.name
                        when "Early" %>
                      <%= link_to user_shift_path(user_shift), class: "calendar-shift-link" do %>
                        <div class="calendar-shift-timeslot-early"><%= t 'early' %></div>
                      <% end %>
                    <% when "Late" %>
                      <%= link_to user_shift_path(user_shift), class: "calendar-shift-link" do %>
                        <div class="calendar-shift-timeslot-late"><%= t 'late' %></div>
                      <% end %>
                    <% when "Night" %>
                      <%= link_to user_shift_path(user_shift), class: "calendar-shift-link" do %>
                        <div class="calendar-shift-timeslot-night"><%= t 'night' %></div>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="calendar-dates-days-day-openshifts">
              <% if open_user_shifts.any? { |u_shift| u_shift.shift.date.day == day && u_shift.shift.date.month == month && !u_shift.user && u_shift.shift.date > DateTime.now } %>
                <div class="calendar-shift-circle calendar-shift-circle--emergency"><i class="fas fa-bell"></i></div>
              <% elsif open_user_shifts.any? { |u_shift| u_shift.shift.date.day == day && u_shift.shift.date.month == month && u_shift.shift.date > DateTime.now } %>
                <div class="calendar-shift-circle"><i class="fas fa-bell"></i></div>
              <% end %>
            </div>
          </div>
        <% end %>
        <% days[:next_month].each do |day| %>
          <div class="calendar-dates-days-day calendar-dates-days-day--next">
            <div class="calendar-dates-days-day-number">
              <%= day %>
            </div>
            <div class="calendar-dates-days-day-myshift">
              <% my_user_shifts.each do |user_shift| %>
                <% if user_shift.shift.date.day == day && user_shift.shift.date.month == current.next_month.month %>
                  <div class="calendar-shift">
                    <% case user_shift.shift.slot.name
                        when "Early" %>
                      <div class="calendar-shift-timeslot-early calendar-shift-timeslot-early--next"><%= t 'early' %></div>
                    <% when "Late" %>
                      <div class="calendar-shift-timeslot-late calendar-shift-timeslot-late--next"><%= t 'late' %></div>
                    <% when "Night" %>
                      <div class="calendar-shift-timeslot-night calendar-shift-timeslot-night--next"><%= t 'night' %></div>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="calendar-dates-days-day-openshifts">
              <% if open_user_shifts.any? { |u_shift| u_shift.shift.date.day == day && u_shift.shift.date.month == current.next_month.month && u_shift.shift.date > DateTime.now } %>
                <div class="calendar-shift-circle"><i class="fas fa-bell"></i></div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="calendar-dates-month">
        <div>
          <%= link_to shifts_with_calendar_path(year: current.last_month.year, month: current.last_month.month ),
          class: "calendar-dates-month-arrows",
          remote: true,
          data: {
            action: "click->calendar#navigate"
          } do %>
          <i class="fas fa-caret-square-left"></i>
          <% end %>
        </div>
        <div><%= mth %> <%= year %></div>
        <div>
          <%= link_to shifts_with_calendar_path(year: current.next_month.year, month: current.next_month.month ),
          class: "calendar-dates-month-arrows",
          remote: true,
          data: {
            action: "click->calendar#navigate"
          } do %>
          <i class="fas fa-caret-square-right"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user_shifts/index.html.erb
<% if @year %>
    <%= render 'calendar', my_user_shifts: @my_user_shifts,
                           open_user_shifts: @open_user_shifts,
                           year: @year,
                           month: @month,
                           mth: @mth,
                           days: @days,
                           current: @current %>
<% end %>

app/views/user_shifts/show.html.erb
<div class="show-box <%= "show-box--early" if @user_shift.shift.slot.name == "Early" && @user_shift.user_id != nil %>
                     <%= "show-box--late" if @user_shift.shift.slot.name == "Late" && @user_shift.user_id != nil %>
                     <%= "show-box--night" if @user_shift.shift.slot.name == "Night" && @user_shift.user_id != nil %>
                     <%= "show-box--emergency" if @user_shift.open && @user_shift.user_id == nil %>">
  <div class="d-flex justify-content-between text">
    <h1 id="shift-title"><%= t 'early' if @user_shift.shift.slot.name == "Early" %>
                         <%= t 'late' if @user_shift.shift.slot.name == "Late" %>
                         <%= t 'night' if @user_shift.shift.slot.name == "Night" %>
      <% if @user_shift.shift.users.include?(current_user) %>
        <img class="avatar-bordered avatar-bordered--small" src="<%= cl_image_path(current_user.photo.key, width: 75, height: 75, crop: :thumb, gravity: :face) %>" alt="avatar-image">
      <% end %>
    </h1>
    <h3 class="shift-card-date-p">
      <%= params[:locale] == 'de' ? l(@user_shift.shift.date, format: "%d. %b") : l(@user_shift.shift.date, format: "%b %d") %>
    </h3>
  </div>
  <div class="shift-card-info-box">

      <div class="text shift-card-text time">
        <i class="shift-card-icon fas fa-clock i"></i>
        <%= @user_shift.shift.slot.start_time.strftime("%H:%M") %> - <%= @user_shift.shift.slot.end_time.strftime("%H:%M") %>
      </div>
      <div class="text shift-card-text points">
        <i class="fas fa-coins i shift-card-icon"></i>
        <%= @user_shift.bonus_points %> bps
      </div>


    <div class="text shift-card-text shift-infos">
      <i class="fas fa-info-circle i shift-card-icon"></i>
      <%= @user_shift.details %>
    </div>
    <div class="text shift-card-text">
      <div class="text shift-card-text">
        <i class="fas fa-users i shift-card-icon"></i>
        <%= t 'colleagues_on_shift' %>
      </div>
      <div class="shift-card-colleagues-avatar d-flex justify-content-around">
        <% @user_shift.shift.users.each do |user| %>
          <% unless user == current_user %>
            <%= link_to user_path(user) do %>
              <img src="<%= cl_image_path(user.photo.key, width: 75, height: 75, crop: :thumb, gravity: :face) %>" alt="avatar-image" class="avatar-bordered shift-card-avatar">
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% if !@user_shift.open && @user_shift.user == current_user %>
    <div class="offer-shift">
      <%= simple_form_for @user_shift, url: offer_shift_path do |f| %>
        <%= f.input :bonus_points, label: params[:locale] == 'de' ? "Möchtest du Bonuspunkte für die Schicht anbieten?" : "Would you like to offer some bonus points with your shift?", :error_html => { :id => "bonus_points_error" }, class:"font-weight-bold" %>
        <%= f.hidden_field :open, value: true %>
        <%= f.button :submit, params[:locale] == 'de' ? "Schicht anbieten" : "Offer Shift", class:"btn btn-primary shift-show-btn" %>
      <% end %>
    </div>
  <% end %>
  <% if @user_shift.open && @user_shift.user == current_user %>
    <div class="offer-shift">
      <div class="offered-alert"><p><%= t 'offered_up' %></p></div>
      <div>
        <%= link_to retract_offer_path(@user_shift),
        data: {
          controller: "offer",
          action: "click->retract"
        } do %>
          <p class="btn btn-primary mb-0 shift-show-btn"><%= t 'change_mind' %></p>
        <% end %>
      </div>
    </div>
  <% end %>
  <% if @user_shift.open && @user_shift.user != current_user %>
    <div class="take-shift-btn">
      <%= link_to accept_shift_path(@user_shift) do %>
        <p class="btn btn-primary mb-0 take-over-button"><%= t 'take_over' %></p>
      <% end %>
    </div>
  <% end %>
  <div class="container user-shift comments-box">
    <p class="comment"><%= t 'conversation' %></p>
    <div class="messages" data-controller="user-shift-subscription"
      data-user-shift-subscription-user-shift-id-value="<%= @user_shift.id %>">
      <% @user_shift.messages.each do |message| %>
        <%= render "messages/message", message: message %>
      <% end %>
    </div>
  </div>
  <%= simple_form_for [@user_shift, @message], remote: true do |f| %>
    <%= f.input :content, label: false, placeholder: params[:locale] == 'de' ? "Nachricht ##{l(@user_shift.shift.date, format: "%d. %b")}" : "Message ##{l(@user_shift.shift.date, format: "%b %d")}" %>
  <% end %>
</div>