config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root to: 'pages#home'
    resources :shifts, only: %i[index]
    get '/shifts/calendar/:year/:month/', to: 'user_shifts#index', as: :shifts_with_calendar
    get '/shifts/calendar', to: 'user_shifts#index', as: :shifts_this_month_with_calendar
    patch 'shifts/:id/offer', to: 'user_shifts#offer', as: :offer_shift
    get 'shifts/:id/retract_offer', to: 'user_shifts#retract_offer', as: :retract_offer
    get 'shifts/:id/accept', to: 'user_shifts#accept', as: :accept_shift
    resources :user_shifts, only: %i[show] do
      resources :messages, only: :create
    end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    get '/profile', to: 'pages#profile'
    resources :users, only: %i[index show]
  end
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :slot
  has_many :user_shifts
  has_many :users, through: :user_shifts
  has_many :messages, through: :user_shifts

  validates :date, presence: true

  def user_on_shift?(user)
    users.include?(user)
  end

  def latest_message
    messages.order(created_at: :desc).first
  end

  def unread_messages?(date, user)
    message = latest_message
    message && message.created_at > date && message.user != user
  end
end

app/views/pages/home.html.erb
<%if user_signed_in? %>
  <div class="wrapper">
    <h2><%= t 'hello' %> <%= current_user.first_name %> </h2>
    <div class="shift-box">
      <h2 class="shift-box-heading"><%= t 'next_shift' %></h2>
      <div class="shift-card <%= "shift-card--early" if @next_user_shift.shift.slot.name == "Early" %>
                             <%= "shift-card--late" if @next_user_shift.shift.slot.name == "Late" %>
                             <%= "shift-card--night" if @next_user_shift.shift.slot.name == "Night" %>"
        data-bs-toggle="collapse" data-bs-target="#nextShift" aria-expanded="false" aria-controls="nextShift">
        <div class="shift-card-left-side">
          <h3 class="shift-card-left-side-title"><%= t 'early' if @next_user_shift.shift.slot.name == "Early" %>
                                                 <%= t 'late' if @next_user_shift.shift.slot.name == "Late" %>
                                                 <%= t 'night' if @next_user_shift.shift.slot.name == "Night" %>
            <% if @next_user_shift.shift.user_on_shift?(current_user) %>
              <img class="avatar-bordered avatar-bordered--small" src="<%= cl_image_path(current_user.photo.key, width: 75, height: 75, crop: :thumb, gravity: :face) %>" alt="avatar-image">
            <% end %>
          </h3>
          <div class="d-flex align-items-center">
          <p class="shift-card-time"><i class="shift-card-icon fas fa-clock"></i>&nbsp&nbsp<%= @next_user_shift.shift.slot.start_time.strftime("%H:%M") %> - <%= @next_user_shift.shift.slot.end_time.strftime("%H:%M") %></p>
          </div>
        </div>
        <div class="shift-card-right-side">
          <p class="shift-card-date"><%= params[:locale] == 'de' ? l(@next_user_shift.shift.date, format: "%d. %b") : l(@next_user_shift.shift.date, format: "%b %d") %></p>
          <% unless @next_user_shift.bonus_points == 0 %>
            <div class="d-flex align-items-center">
              <p class="shift-card-points"><i class="shift-card-icon fas fa-coins"></i>&nbsp&nbsp<%= @next_user_shift.bonus_points %> bps</p>
            </div>
          <% end %>
        </div>
        <div class="collapse mt-1 shift-card-container" id="nextShift">
          <div class="shift-card-container-drop">
            <div class="shift-card-container-drop-avatars">
              <% @next_user_shift.shift.user_ids.each do |user_id| %>
                <% user=User.find(user_id) %>
                <% unless user == current_user %>
                  <img src="<%= cl_image_path(user.photo.key, width: 75, height: 75, crop: :thumb, gravity: :face) %>" alt="avatar-image" class="avatar-bordered shift-card-avatar">
                <% end %>
              <% end %>
            </div>
            <strong>Details</strong>
            <p class="shift-card-container-drop-details"><%= @next_user_shift.details %></p>
            <%= link_to user_shift_path(@next_user_shift), class: "shift-card-icon-link" do %>
              <i class="shift-card-icon-info fas fa-info-circle"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="shift-box shift-box--emergency">
      <h2 class="shift-box--emergency-heading"><%= t 'emergencies' %> <i class="fas fa-exclamation-triangle"></i></h2>
      <% @emergency_shifts.each do |u_shift| %>
        <div class="shift-card shift-card--emergency" data-bs-toggle="collapse" data-bs-target="#cardForShift<%= u_shift.id %>" aria-expanded="false" aria-controls="cardForShift<%= u_shift.id %>">
          <div class="shift-card-left-side">
            <h3 class="shift-card-left-side-title"><%= t 'early' if u_shift.shift.slot.name == "Early" %>
                                                   <%= t 'late' if u_shift.shift.slot.name == "Late" %>
                                                   <%= t 'night' if u_shift.shift.slot.name == "Night" %>
              <% if u_shift.shift.user_on_shift?(current_user) %>
                <img class="avatar-bordered avatar-bordered--small" src="<%= cl_image_path(current_user.photo.key, width: 75, height: 75, crop: :thumb, gravity: :face) %>" alt="avatar-image">
              <% end %>
            </h3>
            <div class="d-flex align-items-center">
              <p class="shift-card-time"><i class="shift-card-icon fas fa-clock"></i>&nbsp&nbsp<%= u_shift.shift.slot.start_time.strftime("%H:%M") %> - <%= u_shift.shift.slot.end_time.strftime("%H:%M") %></p>
            </div>
          </div>
          <div class="shift-card-right-side">
            <p class="shift-card-date"><%= params[:locale] == 'de' ? l(u_shift.shift.date, format: "%d. %b") : l(u_shift.shift.date, format: "%b %d") %></p>
            <% unless u_shift.bonus_points == 0 %>
              <div class="d-flex align-items-center">
                <p class="shift-card-points"><i class="shift-card-icon fas fa-coins"></i>&nbsp&nbsp<%= u_shift.bonus_points %> bps</p>
              </div>
            <% end %>
          </div>
          <div class="collapse mt-1 shift-card-container" id="cardForShift<%= u_shift.id %>">
            <div class="shift-card-container-drop">
              <div class="shift-card-container-drop-avatars">
                <% u_shift.shift.user_ids.each do |user_id| %>
                  <% user=User.find(user_id) %>
                  <% unless user == current_user %>
                    <img src="<%= cl_image_path(user.photo.key, width: 75, height: 75, crop: :thumb, gravity: :face) %>" alt="avatar-image" class="avatar-bordered shift-card-avatar">
                  <% end %>
                <% end %>
              </div>
              <strong>Details</strong>
              <div class="details">
                <p class="shift-card-container-drop-details"><%= u_shift.details %></p>
              </div>
              <div class="shift-card-container-drop-buttons">
                <%= link_to user_shift_path(u_shift), class: "shift-card-icon-link" do %>
                  <i class="shift-card-icon-info fas fa-info-circle"></i>
                <% end %>
                <% unless u_shift.shift.user_on_shift?(current_user) %>
                  <%= link_to accept_shift_path(u_shift) do %>
                    <p class="btn btn-primary mb-0 take-over-button"><%= t 'take_over' %></p>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="shift-box">
      <h2 class="shift-box-heading"><%= t 'other_open_shifts' %></h2>
      <% @open_shifts.each do |u_shift| %>
        <div class="shift-card <%= "shift-card--early" if u_shift.shift.slot.name == "Early" %>
                               <%= "shift-card--late" if u_shift.shift.slot.name == "Late" %>
                               <%= "shift-card--night" if u_shift.shift.slot.name == "Night" %>"
        data-bs-toggle="collapse" data-bs-target="#cardForShift<%= u_shift.id %>" aria-expanded="false" aria-controls="cardForShift<%= u_shift.id %>">
          <div class="shift-card-left-side">
            <h3 class="shift-card-left-side-title shift-card-active"><%= t 'early' if u_shift.shift.slot.name == "Early" %>
                                                                     <%= t 'late' if u_shift.shift.slot.name == "Late" %>
                                                                     <%= t 'night' if u_shift.shift.slot.name == "Night" %>
              <% if u_shift.shift.user_on_shift?(current_user) %>
                <img class="avatar-bordered avatar-bordered--small" src="<%= cl_image_path(current_user.photo.key, width: 75, height: 75, crop: :thumb, gravity: :face) %>" alt="avatar-image">
              <% end %>
            </h3>
            <div class="d-flex align-items-center">
              <p class="shift-card-time shift-card-active"><i class="shift-card-icon fas fa-clock shift-card-active"></i>&nbsp&nbsp<%= u_shift.shift.slot.start_time.strftime("%H:%M") %> - <%= u_shift.shift.slot.end_time.strftime("%H:%M") %></p>
            </div>
          </div>
          <div class="shift-card-right-side">
            <p class="shift-card-date"><%= params[:locale] == 'de' ? l(u_shift.shift.date, format: "%d. %b") : l(u_shift.shift.date, format: "%b %d") %></p>
            <% unless u_shift.bonus_points == 0 %>
              <div class="d-flex align-items-center">
                <p class="shift-card-points shift-card-active"><i class="shift-card-icon fas fa-coins shift-card-active"></i>&nbsp&nbsp<%= u_shift.bonus_points %> bps</p>
              </div>
            <% end %>
          </div>
          <div class="collapse mt-1 shift-card-container" id="cardForShift<%= u_shift.id %>">
            <div class="shift-card-container-drop">
              <div class="shift-card-container-drop-avatars">
                <% u_shift.shift.user_ids.each do |user_id| %>
                  <% user=User.find(user_id) %>
                  <% unless user == current_user %>
                    <img src="<%= cl_image_path(user.photo.key, width: 75, height: 75, crop: :thumb, gravity: :face) %>" alt="avatar-image" class="avatar-bordered shift-card-avatar <%= "shift-card-avatar--highlight" if user == u_shift.user %>">
                  <% end %>
                <% end %>
              </div>
              <strong>Details</strong>
              <div class="details">
                <p class="shift-card-container-drop-details"><%= u_shift.details %></p>
              </div>
              <div class="shift-card-container-drop-buttons">
                <%= link_to user_shift_path(u_shift), class: "shift-card-icon-link" do %>
                  <i class="shift-card-icon-info fas fa-info-circle"></i>
                <% end %>
                <% unless u_shift.shift.user_on_shift?(current_user) %>
                  <%= link_to accept_shift_path(u_shift) do %>
                    <p class="btn btn-primary mb-0 take-over-button"><%= t 'take_over' %></p>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="background-image">
    <div class="banner-landing-page">
      <h1 id="h1-tag"><strong>Shifted</strong></h1>
      <p id="p-tag"><strong><%= t 'subtitle' %>.</strong></p>
      <p><%= t 'login-data' %>:<br>
      E-Mail: Karl.Wonder@mailbox.com<br>
      <%= t 'password' %>: coachoo</p>
      <%= link_to 'Login', new_user_session_path, class: "btn btn-warning login-btn" %>
      <div class="language-buttons">
        <%= link_to 'View site in english', root_path(locale: :en), class: "btn language-btn" if params[:locale] == 'de' || params[:locale] == nil %>
        <%= link_to 'Seite auf deutsch ansehen', root_path(locale: :de), class: "btn language-btn" if params[:locale] == 'en' %>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/profile.html.erb
<div class="d-flex flex-column align-items-center justify-content-center">
  <br>
  <h2><strong><%= t 'your_profile' %></strong></h2>
  <div class="col1 avatar-box">
    <% unless current_user.photo.attached? %>
      <img src="<%= asset_path('default_avatar.png') %>" width="40" alt="default-avatar-image" class="card-trip-user avatar-bordered">
    <% else %>
      <img src="<%= cl_image_path(current_user.photo.key, width: 120, height: 120, crop: :thumb, gravity: :face) %>" alt="avatar-image" class="card-trip-user avatar-bordered">
    <% end %>
  </div>
  <div class="col2 box">
    <div class="d-flex justify-content-between">
      <h3 id="name"><strong><%= current_user.first_name %>&nbsp<%= current_user.last_name %></strong></h3>
      <i class="fas fa-pencil-alt pencil"></i>
    </div>
    <div class="parent-box">
      <div class="text">
        <i class="fas fa-book-medical i"></i>
        <%= current_user.experience_level %>
      </div>
      <div class="text">
        <i class="fas fa-user-tie i"></i>
        <%= current_user.functional_role.name %>
      </div>
      <div class="text">
        <i class="fas fa-coins i"></i>
        <%= current_user.bonus_points %> bps
      </div>
      <div class="quote">
        <i class="fas fa-bullhorn shout"></i></i>
        "<%= current_user.additional_infos %>"
      </div>
    </div>
  </div>
  <div class="col3 box">
    <div class="d-flex justify-content-between">
      <h3 id="name"><strong><%= t 'current_prizes' %></strong></h3>
    </div>
    <div class="parent-box">
      <% Prize.all.each do |prize| %>
        <div class="text">
          <i class="fas fa-award i"></i>
          <%= prize.bonus_points %> <%= t 'bps_for' %>:
          <%= prize.prize %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="preferred-slots">
    <h3 class="preferred-slot-tag"><strong><%= t 'your_preferred_slots' %></strong></h3>
    <div class="grid-container">
      <div class="grid-item"></div>
      <div class="grid-item slot-label-early"><%= t 'early' %></div>
      <div class="grid-item slot-label-late"><%= t 'late' %></div>
      <div class="grid-item slot-label-night"><%= t 'night' %></div>
      <div class="grid-item day"><%= t 'monday' %></div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-early" value="monday1" checked>
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-late" value="monday2" >
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-night" value="monday3" >
      </div>
      <div class="grid-item day"><%= t 'tuesday' %></div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-early" value="tuesday1" checked>
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-late" value="tuesday2" >
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-night" value="tuesday3" >
      </div>
      <div class="grid-item day"><%= t 'wednesday' %></div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-early" value="wednesday1" >
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-late" value="wednesday2" checked>
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-night" value="wednesday3" >
      </div>
      <div class="grid-item day"><%= t 'thursday' %></div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-early" value="thursday1" >
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-late" value="thursday2" >
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-night" value="thursday3" checked>
      </div>
      <div class="grid-item day"><%= t 'friday' %></div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-early" value="friday1" >
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-late" value="friday2" checked>
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-night" value="friday3" >
      </div>
      <div class="grid-item day"><%= t 'saturday' %></div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-early" value="saturday1" >
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-late" value="saturday2" >
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-night" value="saturday3" checked>
      </div>
      <div class="grid-item day"><%= t 'sunday' %></div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-early" value="sunday1" >
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-late" value="sunday2" checked>
      </div>
      <div class="grid-item check-box-container">
        <input class="form-check-input" type="checkbox" name="slot-checkbox" id="slot-checkbox-night" value="sunday3" >
      </div>
    </div>
  </div>
  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "profile-logout-button" %>
</div>